- name: Update and cache apt-get
  apt: update_cache=yes cache_valid_time=3600

- name: Install common packages
  apt: name={{item}} state=present
  with_items:
    - python-pip
    - git
    - git-gui
    - vim
    - mysql-server
    - curl
    - libpq-dev
    - libmagickwand-dev
    - nodejs
    - postgresql
    - postgresql-contrib
    - python-dev
    - mysql-client
    - libmysqlclient-dev
    - redis-server
    - indicator-multiload
  tags: install_packages

- name: Install heroku toolbelt
  sudo: no
  shell: wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  tags: heroku

- name: Create Projects directory
  file: path={{local_home}}/Projects2 state=directory
  sudo: no
  tags: project_dir

- name: Create ~/.bash_profile
  template: >
    src=bash_profile.j2
    dest={{local_home}}/.bash_profile
  notify: reload bash_profile
  tags: bash_profile

- name: Highlight selected tab terminal
  template: >
    src=gtk.css.j2
    dest={{local_home}}/.config/gtk-3.0/gtk.css
  tags: terminal
